# Generated by Django 2.2.12 on 2020-06-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '地区表',
            },
        ),
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50, verbose_name='盘符')),
                ('mountpoint', models.CharField(max_length=50, verbose_name='挂载点')),
                ('fstype', models.CharField(max_length=50, verbose_name='磁盘类型')),
                ('opts', models.CharField(max_length=50, verbose_name='磁盘权限')),
                ('total', models.CharField(max_length=50, verbose_name='容量')),
            ],
            options={
                'verbose_name_plural': '磁盘表',
            },
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='网卡名称')),
                ('family', models.CharField(max_length=50, verbose_name='类型')),
                ('address', models.CharField(max_length=50, verbose_name='IP')),
                ('netmask', models.CharField(max_length=50, verbose_name='子关掩码')),
                ('broadcast', models.CharField(max_length=50, verbose_name='广播地址')),
            ],
            options={
                'verbose_name_plural': '网卡表',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '业务系统',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='标签')),
            ],
            options={
                'verbose_name_plural': '标签表',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='姓名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('phone', models.CharField(max_length=32, verbose_name='手机')),
                ('email', models.EmailField(max_length=254, verbose_name='姓名')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type_id', models.IntegerField(choices=[(1, '服务器'), (2, '交换机'), (3, '防火墙')], default=1, verbose_name='服务器类型')),
                ('device_status_id', models.IntegerField(choices=[(1, '上架'), (2, '在线'), (3, '离线'), (4, '下架')], default=1, verbose_name='服务器状态')),
                ('ipaddr', models.CharField(max_length=128, unique=True, verbose_name='IP')),
                ('hostname', models.CharField(max_length=128, verbose_name='主机名')),
                ('os_platform', models.CharField(blank=True, max_length=32, null=True, verbose_name='操作系统')),
                ('os_version', models.CharField(blank=True, max_length=32, null=True, verbose_name='保证系统版本')),
                ('manufacturer', models.CharField(blank=True, max_length=64, null=True, verbose_name='制造商')),
                ('model', models.CharField(blank=True, max_length=64, null=True, verbose_name='型号')),
                ('sn', models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='SN号')),
                ('idc', models.CharField(blank=True, max_length=50, null=True, verbose_name='机房')),
                ('cabinet', models.CharField(blank=True, max_length=50, null=True, verbose_name='机柜位置')),
                ('cpu_count', models.IntegerField(blank=True, null=True, verbose_name='CPU个数')),
                ('cpu_physical_count', models.IntegerField(blank=True, null=True, verbose_name='CPU物理个数')),
                ('cpu_model', models.CharField(blank=True, max_length=128, null=True, verbose_name='CPU型号')),
                ('mem_total', models.CharField(blank=True, max_length=50, null=True, verbose_name='内存总量')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respository.Area', verbose_name='地区')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respository.Product', verbose_name='业务系统')),
                ('tag', models.ManyToManyField(blank=True, null=True, to='respository.Tag')),
            ],
            options={
                'verbose_name_plural': '服务器表',
            },
        ),
        migrations.CreateModel(
            name='NetDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes_sent', models.CharField(max_length=50, verbose_name='已发送字节')),
                ('bytes_recv', models.CharField(max_length=50, verbose_name='已接收字节')),
                ('packets_sent', models.CharField(max_length=50, verbose_name='已发送包')),
                ('packets_recv', models.CharField(max_length=50, verbose_name='已接收包')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('net', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respository.Net')),
            ],
            options={
                'verbose_name_plural': '网卡信息表',
            },
        ),
        migrations.AddField(
            model_name='net',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='net', to='respository.Server'),
        ),
        migrations.CreateModel(
            name='Mem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_total', models.CharField(max_length=50, verbose_name='总内存')),
                ('used', models.CharField(max_length=50, verbose_name='已使用内存')),
                ('free', models.CharField(max_length=50, verbose_name='空闲内存')),
                ('percent', models.CharField(max_length=50, verbose_name='使用率')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respository.Server')),
            ],
            options={
                'verbose_name_plural': '内存信息表',
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='respository.Server')),
            ],
            options={
                'verbose_name_plural': '错误日志表',
            },
        ),
        migrations.CreateModel(
            name='DiskDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=50, verbose_name='总容量')),
                ('used', models.CharField(max_length=50, verbose_name='已使用容量')),
                ('free', models.CharField(max_length=50, verbose_name='空闲容量')),
                ('percent', models.CharField(max_length=50, verbose_name='使用率')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('disk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respository.Disk')),
            ],
            options={
                'verbose_name_plural': '磁盘信息表',
            },
        ),
        migrations.AddField(
            model_name='disk',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disk', to='respository.Server'),
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_avg', models.CharField(max_length=50, verbose_name='平均使用率')),
                ('percent_per', models.CharField(max_length=50, verbose_name='每个CPU使用率')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respository.Server')),
            ],
            options={
                'verbose_name_plural': 'CPU信息表',
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='respository.Server')),
            ],
            options={
                'verbose_name_plural': '修改日志表',
            },
        ),
    ]
