# Generated by Django 2.2.12 on 2020-06-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respository', '0002_server_is_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disk',
            name='device',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='盘符'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='fstype',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='磁盘类型'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='mountpoint',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='挂载点'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='opts',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='磁盘权限'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='容量'),
        ),
        migrations.AlterField(
            model_name='diskdetail',
            name='free',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='空闲容量'),
        ),
        migrations.AlterField(
            model_name='diskdetail',
            name='percent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='使用率'),
        ),
        migrations.AlterField(
            model_name='diskdetail',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='总容量'),
        ),
        migrations.AlterField(
            model_name='diskdetail',
            name='used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已使用容量'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='free',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='空闲内存'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='mem_total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='总内存'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='percent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='使用率'),
        ),
        migrations.AlterField(
            model_name='mem',
            name='used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已使用内存'),
        ),
        migrations.AlterField(
            model_name='net',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='net',
            name='family',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='net',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='网卡名称'),
        ),
        migrations.AlterField(
            model_name='net',
            name='netmask',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='子关掩码'),
        ),
        migrations.AlterField(
            model_name='netdetail',
            name='bytes_recv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已接收字节'),
        ),
        migrations.AlterField(
            model_name='netdetail',
            name='bytes_sent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已发送字节'),
        ),
        migrations.AlterField(
            model_name='netdetail',
            name='packets_recv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已接收包'),
        ),
        migrations.AlterField(
            model_name='netdetail',
            name='packets_sent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已发送包'),
        ),
        migrations.AlterField(
            model_name='server',
            name='is_sync',
            field=models.BooleanField(default=False, verbose_name='已同步'),
        ),
    ]
