# Generated by Django 2.2.12 on 2020-06-02 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respository', '0004_auto_20200601_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelog',
            name='title',
        ),
        migrations.AlterField(
            model_name='changelog',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to='respository.Server'),
        ),
        migrations.AlterField(
            model_name='disk',
            name='device',
            field=models.CharField(max_length=50, verbose_name='盘符'),
        ),
    ]
