# Generated by Django 2.2.12 on 2020-06-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respository', '0006_auto_20200603_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cabinet',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='机柜位置'),
        ),
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='server',
            name='os_version',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='操作系统版本'),
        ),
        migrations.AlterField(
            model_name='server',
            name='sn',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='SN号'),
        ),
    ]
