# Generated by Django 2.2.12 on 2020-06-05 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respository', '0007_auto_20200604_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=50, null=True, verbose_name='总内存')),
                ('used', models.CharField(blank=True, max_length=50, null=True, verbose_name='已使用内存')),
                ('free', models.CharField(blank=True, max_length=50, null=True, verbose_name='空闲内存')),
                ('percent', models.CharField(blank=True, max_length=50, null=True, verbose_name='使用率')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='swap', to='respository.Server', verbose_name='服务器')),
            ],
            options={
                'verbose_name_plural': '交换分区表',
            },
        ),
    ]
