# Generated by Django 2.2.12 on 2020-06-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('respository', '0008_swap'),
    ]

    operations = [
        migrations.AddField(
            model_name='net',
            name='bytes_recv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已接收字节'),
        ),
        migrations.AddField(
            model_name='net',
            name='bytes_sent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已发送字节'),
        ),
        migrations.AddField(
            model_name='net',
            name='packets_recv',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已接收包'),
        ),
        migrations.AddField(
            model_name='net',
            name='packets_sent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已发送包'),
        ),
        migrations.AlterField(
            model_name='swap',
            name='free',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='空闲Swap'),
        ),
        migrations.AlterField(
            model_name='swap',
            name='total',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='总Swap'),
        ),
        migrations.AlterField(
            model_name='swap',
            name='used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='已使用Swap'),
        ),
        migrations.DeleteModel(
            name='NetDetail',
        ),
    ]
