# Generated by Django 2.2.12 on 2020-06-05 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('respository', '0009_auto_20200605_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl', to='respository.Server', verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='net',
            name='bytes_recv',
            field=models.CharField(default=0, max_length=50, verbose_name='已接收字节'),
        ),
        migrations.AlterField(
            model_name='net',
            name='bytes_sent',
            field=models.CharField(default=0, max_length=50, verbose_name='已发送字节'),
        ),
        migrations.AlterField(
            model_name='net',
            name='packets_recv',
            field=models.CharField(default=0, max_length=50, verbose_name='已接收包'),
        ),
        migrations.AlterField(
            model_name='net',
            name='packets_sent',
            field=models.CharField(default=0, max_length=50, verbose_name='已发送包'),
        ),
    ]
